<?php
/**
 * Created by PhpStorm.
 * User: stc392
 * Date: 21/11/16
 * Time: 13:36
 */

require('template/header.phtml') ; ?>

    <form name="register" method="post" action="sortByTitle.php">

        <?php
        $booksDataSet = new BooksDataSet();
        $title = $_POST['bookTitle'];
        $result = $booksDataSet->sortBooksByTitle($title);

        echo "<br>";
        if (isset($_POST['Go'])) {

            if (empty($title))
            {
                echo "<div class=\"col-xs-12 warning\">";
                    echo "Please specify the name of the book first!";
                echo "</div>";
            }
            else if ($result)
            {
                echo "<div class=\"col-xs-12 message\">";
                    echo "Searched Results for <b>$title</b>:";
                echo "</div>";
                echo '<br>';
                echo '<br>';

                foreach ($view->booksDataSet as $bookData) {
                    echo "<div class=\"col-xs-3 book\">";
                    echo '<a href="bookSingle.php?id=' . $bookData->getISBNNo() . '"</a>';
                    echo '<h4>' . $bookData->getTitle() . '</h4>';
                    echo '<img src="images/' . $bookData->getImage() . ' "alt="no picture" height="170" width="130" />';
                    echo "<br>";
                    echo '<b>Author: </b>' . $bookData->getAuthor() . "<br>";
                    echo '<b>Price: </b>' . '£' . $bookData->getPrice() . "<br>";
                    echo "<br>";
                    echo "</div>";
                }
            }
            else {
                echo "<div class=\"col-xs-12 warning\">";
                    echo "**SORRY: match not found for <b>$title</b>!";
                echo "</div>";
            }
        }
        ?>
    </form>

<?php require('template/footer.phtml') ; ?>