<?php
/**
 * Created by PhpStorm.
 * User: stc392
 * Date: 21/11/16
 * Time: 13:36
 */

require('template/header.phtml') ; ?>

    <form name="register" method="post" action="sortByGenre.php">

        <div class="formTitle">
            <h3><b>Search by Genre</b></h3>
            <p><i>Please enter the types of genre in the input box</i></p>
        </div>

        <br/>
        <input type="text" name="genre" size="35">
        <input type="submit" value="Search" name="Submit" />

        <br/>
        <br/>
        <br/>


        <?php
        $booksDataSet = new BooksDataSet();
        $genre = $_POST['genre'];
        $result = $booksDataSet->sortBooksByGenre($genre);

        if (isset($_POST['Submit'])) {
            if (empty($genre))
            {
                echo "<div class=\"col-xs-12 warning\">";
                    echo "Please specify the kind of genre first!";
                echo "</div>";
            }
            else if ($result)
            {
                echo "<div class=\"col-xs-12 message\">";
                    echo "Searched Results for <b>$genre</b>:";
                    echo "</div>";
                echo '<br>';
                echo '<br>';

                foreach ($view->booksDataSet as $bookData) {
                    echo "<div class=\"col-xs-3 book\">";
                        echo '<a href="bookSingle.php?id=' . $bookData->getISBNNo() . '"</a>';
                        echo '<h4>' . $bookData->getTitle() . '</h4>';
                        echo '<img src="images/' . $bookData->getImage() . ' "alt="no picture" height="170" width="130" />';
                        echo "<br>";
                        echo '<b>Author: </b>' . $bookData->getAuthor() . "<br>";
                        echo '<b>Price: </b>' . '£' . $bookData->getPrice() . "<br>";
                        echo "<br>";
                    echo "</div>";
                }
            }
            else {
                echo "<div class=\"col-xs-12 warning\">";
                echo "**SORRY: match not found for <b>$genre</b>!";
                echo "</div>";
            }
        }
        ?>
    </form>

<?php require('template/footer.phtml') ; ?>