    </div>


    <div class="row">
        <div id="footer" class="col-xs-12">
            <p><i>MVC design pattern | Bootstrap CSS framework | ©2016 by Navin Bajgai | All Rights Reserved</i></p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>